### ISSUE TITLE
Add the ability to skip the external monitor feature.

### ISSUE THREAD

**Issue by dionysiusmarquis** [goalque/automate-eGPU#11]
Hi,

it would be nice if it could be possible to use this script just for the web driver installation and kext modification. I did this by commenting out line ``845`` to ``894``. An script option for this scenario would be nice.

**Comment by goalque** [comment]
Can you describe a use case where such a feature would be useful? Lines 845-850 will be removed to resolve issue #8.

**Comment by dionysiusmarquis** [comment]
So far I did the setup following this: http://www.journaldulapin.com/2013/08/24/a-thunderbolt-gpu-on-a-mac-how-to/
I had the idea to write a script to do this steps automated. Then I saw your script which already is capable of this tasks. I'm using the eGPU setup for CUDA tasks and don't need anything more than the Web Driver installation an kext modification. Meaning all the additional features your script is providing aren't necessary in this scenario.

**Comment by goalque** [comment]
The script won’t become notably faster or make CUDA better by skipping AddBoardId function. Already skips it if board-id is found. As I aim to keep the script as compact as possible, supporting both the AMD and Nvidia, one additional option for skipping functionalities would confuse a user.

There is an option, which skips Nvidia web driver downloading, but with a good reason - Kepler architecture eGPU users can use built-in OS X drivers.

However, if someone is working purely with CUDA, an option for automated CUDA driver download would be possible and meaningful. I’ll think about it.
