### ISSUE TITLE
El Capitan issue

### ISSUE THREAD

**Issue by Chrisnoome** [goalque/automate-eGPU#12]
script fails with following error:

*nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found
Boot into recovery partition and type: csrutil disable* 

and returns to the prompt.

GTX 970 in a Sonnet echo express IIID.
Mac Pro 2013. 
OS X 10.11.

**Comment by goalque** [comment]
Do as the script says, disable SIP.
