### ISSUE TITLE
[-clpeak] option is broken

### ISSUE THREAD

**Issue by goalque** [goalque/automate-eGPU#13]
CMake and cl.hpp URLs have changed. They will be fixed in v0.9.8. Here's the correct ones:

https://www.khronos.org/registry/cl/api/2.1/cl.hpp
https://cmake.org/files/v3.3/cmake-3.3.0-Darwin-x86_64.tar.gz

**Comment by agosto-levitomes** [comment]
https://cmake.org/files/v33/cmake-330-Darwin-x86_64targz *

**Comment by goalque** [comment]
Fixed.
