### ISSUE TITLE
0.9.7 not working on MBPro (late 2013, nVidia 750m)?

### ISSUE THREAD

**Issue by frohsinn** [goalque/automate-eGPU#14]
Hi there, got strange behavior here. after running automate-eGPU.sh 0.9.7 everything seems to be fine. it tells system is ready for eGPU. but after rebooting screens keeps black. booting with pram-reset and without external pcie-box ends up in a strange screen with tiny letters and icons and veeeeeery slow response. have read somewhere 0.9.6 would help with dGPU. is that right? where can i get it? or is there an other solution?

thanx in advance!

system:
2,3 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 750M 2048 MB
OS X 10.9.5 (13F1134)
Akitio Thunder2 PCIe Box
nVidia GTX 970 with ePSU

**Comment by frohsinn** [comment]
that's what i get from the script:

*** automate-eGPU.sh v0.9.7 - (c) 2015 by Goalque ***
-------------------------------------------------------
Detected eGPU
 GM204 [GeForce GTX 970]
Current OS X
 10.9.5 13F1134
Previous OS X
 10.9.5 13F34
Latest installed Nvidia web driver
 Version: 334.01.03f06
 Source: 3rd Party
 Install Date: 11.12.15 16:43

Checking IOPCITunnelCompatible keys...

IOPCITunnelCompatible mods are valid.
Mac board-id found.
Searching for matching driver...

Your system is eGPU enabled and Nvidia web driver is up to date.
___________________________________________________

And this is what i get from system profiler:

![sys_profiler_gtx970_via_akitio](https://cloud.githubusercontent.com/assets/16256960/11749054/d2c984d6-a02b-11e5-8132-22522df84b06.jpg)

**Comment by goalque** [comment]
OS X 10.10 is a minimum requirement with Maxwell cards. Since you have Nvidia dedicated graphics, download v0.9.6:
curl -o ~/Desktop/automate-eGPU.sh https://raw.githubusercontent.com/goalque/automate-eGPU/7192c79bda052bff92428700b59b652b30e6ab4d/automate-eGPU.sh
