### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by w4vz** [goalque/automate-eGPU#19]
I had to reset my PRam so have to re-run the script

Doing as usual with instruction provided
chmod +x automate-eGPU.sh goes fine

but when I run sudo automate-egpu.sh it asks me for my password then outputs "command not found".
sudo automate-eGPU.sh 

Am I missing something? Just doing as I did before. I don't understand.

Password:
sudo: automate-eGPU.sh: command not found

Thank you

**Comment by goalque** [comment]
Uninstall the script if you make system changes (such as NVRAM reset). The preferred command is "sudo ./automate-eGPU.sh" in the folder where the file is. After NVRAM reset, the SIP is re-enabled and you have to disable it on El Capitan.

**Comment by w4vz** [comment]
It was SIP indeed. Forgot that these manipulations reset it. Thanks Goalque, all sorted :)
