### ISSUE TITLE
automate-eGPU：there is something wrong with OS X10.11.4

### ISSUE THREAD

**Issue by blueskypig** [goalque/automate-eGPU#22]
When I run ./automate-eGPU, the terminal display:
nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found
Boot into recovery partition and type: csrutil disable

**Comment by irozhkov** [comment]
lol, then "Boot into recovery partition and type: csrutil disable"

**Comment by goalque** [comment]
yep
