### ISSUE TITLE
The script will cause kernel panic based on OS X10.11.4

### ISSUE THREAD

**Issue by blueskypig** [goalque/automate-eGPU#23]
After running the script, I make sure everything is ready and restart my Mac, then the system just reboot again and again. I also try to manually operate the process, which lead to the same result. And, I notice that it might be the change of Kext that contribute to the kernel panic. I hope someone help me to handle the problem. Thank you!

**Comment by blueskypig** [comment]
My equipment are Akihito and GTX750ti, which work perfect under the window.

**Comment by goalque** [comment]
It’s confirmed working on 10.11.4. What is your Mac model identifier? Reset NVRAM, disable SIP, run the script and restart. If that doesn’t help, reinstall OS X. If the kexts are manually messed up, the last option is erase & reinstall OS X.

**Comment by blueskypig** [comment]
Only after erase&reinstall OS X, it can work. However, once I recover the data from time machine,the system will break down again. Thank you for your reply, maybe I should give it up. After all, it can works under win.

**Comment by goalque** [comment]
If only erase and install helped, your time machine backup contains broken kexts. The script takes backup of original kexts automatically into app support folder. Be sure that those kexts are untouched and originals.
