### ISSUE TITLE
Optimus mode is not enabled with script

### ISSUE THREAD

**Issue by andersfischernielsen** [goalque/automate-eGPU#25]
After having run the script, and tested with `-clpeak` that the card is recognised, I still can't use the card for playing games on OS X. 

Every game only detects the Iris card in my MacBook. 
On Windows the GPU works using NVIDIA's Optimus as intended. I'm able to run games that the Iris shouldn't be able to power. 

I've run the script on OS X first without `-a`, rebooted, and then with `-a` after rebooting. 
The GPU is recognised in System Information, but still isn't seen by the games.

**Comment by andersfischernielsen** [comment]
This might not be supported on OS X at all. I couldn't find an answer online. 
If that's the case, you can just close the issue. :)

**Comment by goalque** [comment]
This is frequently asked question. Optimus technology doesn’t exist in OS X. Apps are launched from the screen which is set as the primary, so drag the white menu bar to eGPU screen in display preferences.

**Comment by andersfischernielsen** [comment]
Thanks for answering. Thought that was the case.
