### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by wesleykunze** [goalque/automate-eGPU#26]
*** automate-eGPU.sh v0.9.8 - (c) 2015 by Goalque ***
-------------------------------------------------------
Detected eGPU
 GM200 [GeForce GTX 980 Ti]
Current OS X
 10.11.5 15F18c
Previous OS X
 10.10.4 14E46
Latest installed Nvidia web driver
 Version: 346.03.10b01
 Source: 3rd Party
 Install Date: 4/22/16, 5:03 PM

You are running official Nvidia driver.
Checking IOPCITunnelCompatible keys...

Missing IOPCITunnelCompatible keys.
Mac board-id not found.
Searching for matching driver...

No web driver yet available for build [15F18c].
This script can download and modify the older package [346.03.10b01] (y/n)?
y
No web driver found for OS X 10.11.5.
Would you like search the latest available package for [10.10.4] (y/n)?
y
Operating system id not found. Nvidia may have changed their web driver search service.

**Comment by goalque** [comment]
https://www.techinferno.com/index.php?/forums/topic/9753-egpu-script-not-working/&do=findComment&comment=141859
