### ISSUE TITLE
eGPU and internal monitor on mbp 2014

### ISSUE THREAD

**Issue by thomasvangurp** [goalque/automate-eGPU#28]
Just a short question, is it possible to get the an eGPU to boot automatically and drive the internal monitor on an macbook pro 2014 as well as one or more external monitors?

**Comment by LeeroyDing** [comment]
Windows only. It's not this script's business anyway, better posted on techinferno.

**Comment by goalque** [comment]
Accelerated internal screen under OS X is possible with windowed apps that are started on the eGPU monitor. An external monitor or dummy plug is necessary.
