### ISSUE TITLE
Upgrade to OSX 10.11.6 causes retina iMac to switch to bizarre 2560 x 2880 mode

### ISSUE THREAD

**Issue by Enphilistor** [goalque/automate-eGPU#30]
Hello.  I'm running a retina iMac 27" which is supposed to have a 5120x2880 display.  I've been using automate-eGPU for several months with either one or two AktioThunder2 containing an nVidia GTX745 and a GTX 750Ti.  I upgraded to 10.11.6 last week and after the mandatory re-install and update of the nVidia driver I'm stuck with this bizarre graphics mode.

Instead of 5120x2880 [....] it now looks like 2560x2880 ...[..]... -- I'm absolutely certain that it's the automate-eGPU installation procedure that's causing the issue because I've wiped the machine and re-installed everything and it was fine and 5120x2880, I then re-installed automate-eGPU and boom.  Back to 2560x2880.   Curiously the System info page of OSX says that the display is running 5120x2880 -- but it's definitely not.

Any thoughts or suggestions would be greatly appreciated!
![img_3854](https://cloud.githubusercontent.com/assets/2266405/17124222/294b5d3a-52af-11e6-8b0a-2f4669a8b867.JPG)

**Comment by Enphilistor** [comment]
Forgot to mention that I'm running the nvidia driver 8.0.29 and the web driver 346.03.15f01

**Comment by goalque** [comment]
This is a known issue. Try a quick fix:
https://github.com/goalque/automate-eGPU/issues/17
