### ISSUE TITLE
Sierra 10.12

### ISSUE THREAD

**Issue by natemac** [goalque/automate-eGPU#31]
So I dual booted the 10.12 Public Beta 2. We use Octane Render with eGPUs connected to the Trash Can Mac Pro's.
I have not been able to get the external GPU booted yet, and get some crazy crashes and no boot up with the eGPU is installed. When I run the script (I've already installed the latest NVIDIA & CUDA) I get the following:
```
user-Mac-Pro:automate-eGPU-master user$ sudo ./automate-eGPU.sh
*** automate-eGPU.sh v0.9.8 - (c) 2015 by Goalque ***
-------------------------------------------------------
Detected eGPU
 GM200 [GeForce GTX 980 Ti]
Current OS X
 10.12 16A254g
Previous OS X
 [not found]
Latest installed Nvidia web driver
 Version: 367.05.10.05b07
 Source: 3rd Party
 Install Date: 7/26/16, 4:21 PM

Checking IOPCITunnelCompatible keys...

Missing IOPCITunnelCompatible keys.
Mac board-id not found.
Searching for matching driver...

The latest package for [16A254g] is already downloaded.
Do you want to reinstall? (y/n)
n
Ok.
user-Mac-Pro:automate-eGPU-master user$ 
```

Let me know if there is any way I can help this along, as it's something I use every day.

**Comment by natemac** [comment]
I did attempt to do it the manual way using text Wrangler with no luck either.
The system report shows nothing, not even the NVIDIA Chipset as a GPU.
I made a tutorial to do this awhile back: https://www.youtube.com/watch?v=LePHJ2rG05c

When I attempt to let the script install the driver I get the following.
```
*** automate-eGPU.sh v0.9.8 - (c) 2015 by Goalque ***
-------------------------------------------------------
Detected eGPU
 GM200 [GeForce GTX 980 Ti]
Current OS X
 10.12 16A254g
Previous OS X
 [not found]
Latest installed Nvidia web driver
 Version: 367.05.10.05b07
 Source: 3rd Party
 Install Date: 7/26/16, 4:21 PM

Checking IOPCITunnelCompatible keys...

Missing IOPCITunnelCompatible keys.
Mac board-id not found.
Searching for matching driver...

The latest package for [16A254g] is already downloaded.
Do you want to reinstall? (y/n)
y
installer: Error the package path specified was invalid: '/Library/Application Support/Automate-eGPU/NVIDIA/WebDriver-367.05.10.05b07.pkg'.
Checking IOPCITunnelCompatible keys...

Missing IOPCITunnelCompatible keys.
IOPCITunnelCompatible mods done.
Add: ":IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-F60DEB81FF30ACF6" Entry Already Exists
Board-id added.
NVDARequiredOS does not match. Changed to 16A254g
All ready. Please restart the Mac.
user-Mac-Pro:automate-eGPU-master user$ 
```

**Comment by agosto-levitomes** [comment]
Have you disabled `csrutil`?
I have noticed I do not receive a prompt to disable `csrutil` on the latest version of automate-eGPU (unless I am using the `-uninstall` flag), but it is still required

**Comment by ltomes** [comment]
Have you disabled `csrutil`?
I have noticed I do not receive a prompt to disable `csrutil` on the latest version of automate-eGPU (unless I am using the `-uninstall` flag), but it is still required.

**Comment by natemac** [comment]
Yes, I did run the csrutil today when I tried the script again and the manual install.

**Comment by goalque** [comment]
Never do anything manually with the script, that's a sure way to fail. The script has never supported beta builds but now Nvidia is very friendly, providing also beta links. I don't have much time nowadays. Here's the first part of the solution:

Change line 516 to:
`curl -k -o $TMPDIR"WebDriver-"$download_version".pkg" $download_url`

I give a hint for the rest: the function DeduceStartup(), change 6 characters in two lines.

```
*** automate-eGPU.sh v0.9.8 - (c) 2015 by Goalque ***
-------------------------------------------------------
Detected eGPU
 GM204 [GeForce GTX 980]
Current OS X
 10.12 16A254g
Previous OS X
 [not found]
Latest installed Nvidia web driver
 Version: 367.05.10.05b07
 Source: 3rd Party
 Install Date: 01/08/2016, 15.00

Checking IOPCITunnelCompatible keys...

Missing IOPCITunnelCompatible keys.
Mac board-id not found.
Searching for matching driver...

Driver [367.05.10.05b07] found from:
https://images.nvidia.com/mac/mjjlJqeY2WlA5pZtGJLqstGz7vX4N6l7/WebDriver-367.05.10.05b07.pkg
Do you want to download this driver (y/n)?
y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60.9M  100 60.9M    0     0  3432k      0  0:00:18  0:00:18 --:--:-- 3578k
Driver downloaded.
Removing validation checks...
Modified package ready. Do you want to install (y/n)?
y
installer: Package name is NVIDIA Web Driver 367.05.10.05b07
installer: Upgrading at base path /
installer: The upgrade was successful.
installer: The install requires restarting now.
Checking IOPCITunnelCompatible keys...

Missing IOPCITunnelCompatible keys.
IOPCITunnelCompatible mods done.
Board-id added.
NVDARequiredOS does not match. Changed to 16A254g
All ready. Please restart the Mac.
```

**Comment by jakelaurieNZ** [comment]
Can you disclose those 6 characters yet? I don't have the time to scrape through the function / make guesses

**Comment by goalque** [comment]
Okay. At lines 725 and 754, change `-eq 11` to `-gt 10`

**Comment by rkitover** [comment]
Has anyone tried this and can confirm that it works? (That is, the mac boots, recognizes the card and outputs video to it on 10.12.)

I didn't know about this project and was changing the kext plists as described [here](http://www.journaldulapin.com/2014/12/04/a-nvidia-maxwell-card-with-thunderbolt-on-a-mac-running-yosemite/) for the past few months, and this method didn't work for me for 10.12. That is, with just the plist mods it would boot and I would see the card in system report, but it would refuse to output video to it.

Link to the latest beta drivers is [here](http://www.tonymacx86.com/threads/nvidia-releases-alternate-graphics-drivers-for-macos-sierra-10-12-beta.195315/) btw.

**Comment by jakelaurieNZ** [comment]
I try it in 12 hrs with a 960 and 970. 
Serves us right for using beta software :)

**Comment by goalque** [comment]
You can try v0.9.9 ;) Remember to uninstall the previous version:
sudo ./automate-eGPU.sh -uninstall

**Comment by rkitover** [comment]
Ok well, I got a TM backup of a good 10.11.6 setup, so I might as well give it a go, will try it now and update this thread.

My setup is a 750ti in an akito thunder2 with a radio shack power supply btw.

**Comment by rkitover** [comment]
So I finally tried this, sorry it took me so long, I was trying to figure out if there were issues with [this pixel clock patch](https://github.com/Floris497/mac-pixel-clock-patch-V2).

The script works perfectly, no mods needed, and gets the latest nvidia driver.

As for my system, I am seeing corruption in the top system menu bar and in spotlight and things of this sort. Parts have a black background or are squished together etc.

Here is a screenshot of the menu bar:

![menubar screenshot](https://c3.staticflickr.com/9/8815/28915443802_3235a58d3c_k.jpg)

And here's a screenshot of spotlight:

![spotlight screenshot](https://c8.staticflickr.com/8/7788/28403334703_528cd7b981_k.jpg)

It seems to not be related to the pixel clock patch because it still happens at 1080p.

I am on a mid-2011 mac mini server with a 750Ti in an akito thunder2.

I'm not sure if at this point I should keep this setup and wait for things to improve (the system is usable even with these glitches) or go back to my 10.11.6 backup, any suggestions?

**Comment by rkitover** [comment]
Another odd thing with this configuration, the whole thing crashes a lot when I connect to something with screen sharing.

**Comment by rkitover** [comment]
@jakelaurieNZ any luck on your side? I'm probably going back to 10.11.6.

**Comment by jakelaurieNZ** [comment]
It worked fine for me, I had to reinstall the egpu driver twice though. Maybe this latest driver has issues with the 750ti specifically or its a thunderbolt 1 issue. I'll see what kind of hardware I can get my hands on to test.

**Comment by goalque** [comment]
Stick to 10.11.6. UI glitches and rendering bugs come not as a surprise as Metal framework is continuously developed. My GTX 980 displayed incorrect colors after PB3. RX 480 spit out pixels correctly, also passed Unigine Valley benchmark without wattage drops.

**Comment by rkitover** [comment]
@goalque Thank you, starting TM restore. I'll probably restore this 10.12 setup onto my external to play with.

I'm guessing some of the [issues](https://github.com/Floris497/mac-pixel-clock-patch-V2/pull/62) I had with the [pixel clock patch](https://github.com/Floris497/mac-pixel-clock-patch-V2) and intel iGPU may also have been metal related then.

Speaking of which, would you be interested in a PR to add the pixel clock patch (for boards in model years for which this applies) as an optional step in the automation process?

**Comment by goalque** [comment]
The script is already too complex to maintain, and I want to keep it as simple as possible. And not sure if that would be of any help. I’ve rarely seen resolution issues with an eGPU monitor, regardless of the display interface. The only exception is a 5K iMac (https://github.com/goalque/automate-eGPU/issues/17).

**Comment by rkitover** [comment]
Certainly understandable if you don't want to make it any more complex.

The [pixel clock patch](https://github.com/Floris497/mac-pixel-clock-patch-V2) is for IOKit on <=10.11 and CoreGraphics on 10.12+, what Apple did there was artificially limit the maximum pixel clock for older macs (e.g. 2011 or 2012) such that, regardless of the actual graphics driver being used, you can't go over 1080p. I saw this with both the eGPU and intel graphics until I applied the IOKit patch. I have a mid-2011 mac mini server.

**Comment by LeeroyDing** [comment]
Speaking of Metal, since eGPU acceleration works on Metal applications on the internal display without any configuration, do eGPUs work for internal displays by default on Sierra?

**Comment by dudeoutfitters** [comment]
You GPU may need more wattage, I have a 970 on 2012 quad core mac mini with a 550watt unit. More than what I should have, in a situation like this its best to go with more than what you'll need or you'll be up shit creek.

**Comment by rkitover** [comment]
@dudeoutfitters this is probably the wrong place for this, but I'm using akitio thunder2 with an EVGA 750Ti SC and [this RadioShack power supply](https://www.radioshack.com/products/radioshack-13-8vdc-19a-power-supply?variant=5717083653).

I'm seeing some conflicting information on whether it is enough to power my GPU by just connecting a more powerful PSU to the thunder2, the RadioShack one I linked I believe is 350W, more than sufficient.

Originally I got my info [here](https://www.techinferno.com/index.php?/forums/topic/5661-us189-akitio-thunder2-pcie-box-16gbps-tb2/&page=48#comment-115060).

I am getting crashes occasionally, but I don't believe it's because of power, although I'm not sure. It crashes sometimes completely randomly when I'm not doing anything special, or the screen is even sleeping, yet I can run the Valley benchmark for an hour with perfect stability, in fact I never had it crash when I was running Valley or Furmark, and this is when you would expect it to draw a lot of power, and the other reports of instability I've seen mention that for them it usually crashes after starting a game or w/e.

**Comment by goalque** [comment]
@rkitover 
Many others have made the same mistake:

https://www.techinferno.com/index.php?/forums/topic/7989-script-automating-the-installation-of-egpu-on-os-x-inc-display-output/&do=findComment&comment=141648

https://www.techinferno.com/index.php?/forums/topic/10337-mid-2012-15-mbp%C2%A0%C2%A0gtx750ti10gbps-tb1-akitio-thunder2-120-watt-psu-%C2%A0unstable/&do=findComment&comment=147630

**Comment by ikir83** [comment]
I'm trying my Nvidia GTX 970 on 10.12 without luck. The rendering seems done by the CPU, super slow with glitches. Does we just need Nvidia updated drivers?

**Comment by goalque** [comment]
@ikir83 
Please read the release notes: support for 10.12 is experimental. It’s not the task of the script to handle rendering issues of some application.

**Comment by ikir83** [comment]
@goalque
Sure, but the the glitch and slowness is on the OS itself, even logging in seems a slideshow, does it depends on Nvidia drivers?

**Comment by goalque** [comment]
Yes, Maxwell cards are dependent on the Nvidia’s web driver. Set the eGPU monitor as the primary. DVI/HDMI works better, DP needs improvement.

**Comment by ikir83** [comment]
Thanks i will try with HDMI, otherwise i will unplug my eGPU and wait for new drivers!

**Comment by ikir83** [comment]
What is the correct terminal option to install last est Nvidia beta driver?

**Comment by rkitover** [comment]
Just tried latest Sierra with my new setup using a 980Ti+riser, PSU and barrel adapter. Everything seems to be working great.

Had a couple of weird problems with the script, it didn't want to find the driver, so I installed it myself and added the tunnel key to NVDAStartupWeb.kext myself as well (then ran kext utility.)

**Comment by goalque** [comment]
Thanks Nvidia! Keep up the good work!

https://www.techinferno.com/index.php?/forums/topic/7989-script-automating-the-installation-of-egpu-on-os-x-inc-display-output/&do=findComment&comment=149884

**Comment by rkitover** [comment]
Yeah, I tried the script again a few hours after the sierra final was released, and everything worked perfectly.
