### ISSUE TITLE
rmbp 15 2013 Later with 750M (ME294) / akitio thunder2

### ISSUE THREAD

**Issue by griffinqiu** [goalque/automate-eGPU#34]
I heart that the rmbp 15 with 750M cannot use thunder2 unless disable the 750M card in macOS.

Could the rmbp 15 with 750M use akitio thunder2 in macOS ?

I planning to use 1060 gpu with DELL external display.

My other question is how could I recover it after used automate-eGPU.sh ?

Thanks

**Comment by agosto-levitomes** [comment]
I am using a 2013 mbpr with 750m, with an akitio. 
The setup can boot into windows or osx with the 750m enabled. Sometimes I disable the 750m in benchmarks and see better performance.

**Comment by griffinqiu** [comment]
@agosto-levitomes thanks for you comment ;)

How could I disable the 750m ? 

If I take rmbp to office, could I directly connect the DP of rmbp to Display without recover automate-eGPU.sh ?

BZW which external is GPU you used?

**Comment by agosto-levitomes** [comment]
In OSX I have never disabled the internal gpu (I don't know how one would do that)
In windows I have disabled the internal gpu.

I use `-a

I have used an nvidia 780 and an nvidia 980ti with my setup.

**Comment by griffinqiu** [comment]
So cool !!!
