### ISSUE TITLE
Doesn't work with GTX 1060 6GB on macOS 10.12.1

### ISSUE THREAD

**Issue by iaomw** [goalque/automate-eGPU#39]
![image](https://cloud.githubusercontent.com/assets/2307692/20325063/59a8db74-ab83-11e6-8f07-bee2be593042.png)

It works fine on Windows 10 and I am sure the external screen works. But cannot work on macOS.

**Comment by boxofdeath** [comment]
There currently isn't any macOS driver support for the 10-series cards.

**Comment by cronos45** [comment]
Is there support for 960?

**Comment by AurumNemo** [comment]
Nvidia Web Driver supports 960.

**Comment by YenF** [comment]
I am using GTX1060 3gb, getting the same issue with @iaomw. Still can not run on sierra, hope it can be supported soon.

**Comment by AurumNemo** [comment]
Nvidia drivers are developed by Nvidia officially for Mac Pro 2012. Pascal is quite different from Maxwell, so more time is needed to develop a new driver, but it's not sure if Nvidia will continue.

**Comment by ghochschild** [comment]
Can someone give an update on this now that nvidia released alternate drivers? Does it work with 1060 after installing the drivers?

https://www.tonymacx86.com/threads/nvidia-releases-alternate-graphics-drivers-for-macos-sierra-10-12-3-367-15-10-35.213122/

**Comment by Ricardonacif** [comment]
So the only solution for the 10 series support would be if Apple releases a Mac Pro with those cards?

**Comment by iaomw** [comment]
It's done. Thanks nVidia.
