### ISSUE TITLE
Is it possible to support akitio thunder3 node?

### ISSUE THREAD

**Issue by rudaoshi** [goalque/automate-eGPU#41]
I bought a akitio node (tb3), but found that egpu script report " cannot detect external GPU". 

Akitio said that node is not compatible with macOS. But is it possible that eGPU script to make it usable on macOS?

**Comment by AurumNemo** [comment]
A few days ago AKiTio officially said Apple prevents users from using eGPU over TB 3 on macOS (not only Apple, someone found that Dell had do so), but I think it'll be possible if someone could break the limits.

**Comment by goalque** [comment]
Yes, it’s officially announced:

“We are currently working to make all of our Thunderbolt 3 products **except the Node and the Thunder3 PCIe SSD** compatible with Windows and macOS.”

https://www.akitio.com/blog/articles/akitio-thunderbolt3-devices-macbook-pro

The script automates the process that you can do manually by editing xml files. I am not going to break the limits by binary hacking. However, TB2 DIYers can still benefit from the script.

**Comment by rudaoshi** [comment]
I just tried the tb3-enabler (https://github.com/KhaosT/tb3-enabler). The patch succeeded in my MBP 8.2 and 11.1. But the script still fails.

**Comment by cronos45** [comment]
@ rudaoshi, those are TB @ macs

**Comment by goalque** [comment]
Automate-eGPU.sh is not meant to be combined with the TB3 enabler. Please read the license conditions:

https://github.com/goalque/automate-eGPU/blob/master/SCRIPT-LICENSE.txt

“No one is allowed to modify Apple's copyrighted binary files.”
