### ISSUE TITLE
Akitio Node with GTX980Ti reports no external GPUs detected

### ISSUE THREAD

**Issue by faying** [goalque/automate-eGPU#44]
Thunderbolt device is connected, but no external GPUs detected.
In System information, Akitio Node do not like Thunder 3 report unsupported. However,  there was no eGPU shows on Graphics Card Panel.
Test on iMac 5K 2015, Macbook Pro 13inch 2015 and MacBook Pro 15inch 2016.

Do u have any solutions on it?

**Comment by AurumNemo** [comment]
Node devices are blocked by Apple.
https://github.com/goalque/automate-eGPU/issues/41

**Comment by goalque** [comment]
Try firmware update: https://egpu.io/thunderbolt-egpu-for-mac-2017-update-macos-sierra/
