### ISSUE TITLE
No acceleration (Internal display)

### ISSUE THREAD

**Issue by DenisGrusz** [goalque/automate-eGPU#45]
After I install automate-eGPU I have problem with acceleration on my main internal screen, even the eGPU doesn't plug in. Also the screen seems looks blurry on the 2048x1280 resolution, on 1440x900 it's super sharp. 

I've made some video and screenshots to show how it looks: 
[https://drive.google.com/open?id=0B8ynmra1gIBNMVFVNmNVTUlGczg](url)

Acceleration on the external monitor work perfectly.

**Comment by goalque** [comment]
No links to TI forum please. I've discontinued script development but one friend is willing to continue from v1.0.0 soon.

**Comment by DenisGrusz** [comment]
Than you for the replay. I will wait for v1.0.0 version.

**Comment by goalque** [comment]
https://egpu.io/forums/mac-setup/any-way-at-all-for-running-egpus-in-macos-with-internal-display/#post-1674
