### ISSUE TITLE
New script

### ISSUE THREAD

**Issue by cronos45** [goalque/automate-eGPU#46]
Hi goalque, I know you mentioned someone will take over. Will we be updated here so as to know where to follow?

Thank you!

**Comment by goalque** [comment]
You will be notified here and www.egpu.io

**Comment by AurumNemo** [comment]
When will 1.0.0 released formally? It has been a month since you noticed that. I can see "Pull request" from FricoRico and his beta script, it that 1.00?

**Comment by goalque** [comment]
Ikir is beta testing the new version:

https://egpu.io/forums/mac-setup/macbook-pro-13-2016-touchbar-with-akitio-thunder3-radeon-rx480-work-in-progress/

The estimated release will be within a week.

**Comment by ZooOnClinton** [comment]
any updates?

**Comment by goalque** [comment]
A week has seven days. It's now released :)

**Comment by ZooOnClinton** [comment]
Awesome! Thank you!
