### ISSUE TITLE
Cannot detect the external GPU with asus XG station 2

### ISSUE THREAD

**Issue by iAstro** [goalque/automate-eGPU#47]
Thunderbolt device is connected, but no external GPUs detected.
------------------
MacBook Pro 2016 15' touchbar + macOS 10.12.3
Asus XG station 2 + XFX RX480 4G GPU
------------------
Is it a issue about the XG station or XFX GPU? And how to resolve it? Thank you!

**Comment by iAstro** [comment]
After updating the firmware v23 of XG 2, all issue are resolved, thank you!

**Comment by nando4** [comment]
iAstro, where did you get the XG2 v23 firmware from? How much did the enclosure cost? I'd like to include a link to the firmware update it at the comparison page, and include it's price.

https://egpu.io/external-gpu-buyers-guide-2017/#tb3-enclosures

Thanks,Nando
 

    On Sunday, 5 March 2017, 21:51, iAstro <notifications@github.com> wrote:
 

 After updating the firmware v23 of XG 2, all issue are resolved, thank you!—
