### ISSUE TITLE
Getting this error: Cannot parse a NULL or zero-length data

### ISSUE THREAD

**Issue by sipman** [goalque/automate-eGPU#48]
Hey i get this error: Cannot parse a NULL or zero-length data

I have added a little gif showing the process.

![automate-egpu](https://cloud.githubusercontent.com/assets/6494644/22564778/ff5a4e28-e985-11e6-8023-799fcdabea34.gif)

**Comment by goalque** [comment]
Check you Internet connection.

**Comment by goalque** [comment]
This occurs always when there is no Internet connection or Nvidia's web site doesn't respond. Not a bug.
