### ISSUE TITLE
hotplug not possible | osx crashes when unplug thunder2

### ISSUE THREAD

**Issue by sambP** [goalque/automate-eGPU#49]
Your script is perfect when i boot osx with the akitio thunder2 pluged in. All works great. 

But when the mac is running and i try plug in the thunderbold cable nothing happens. I musst reboot. Is there any way to fix this?

If I unplug the cable while running, the mac always crashes. But this is not a problem for me.

(GTX 970, Akitio Thunder2, Sierra 10.12.3, MacBook Pro mid 2014, -a)

**Comment by braynshock** [comment]
That is due to the fact that Apple does not support external thunderbolt based GPUs, and by extension hot-plugging external GPUs is not supported. If you were using a non-GPU PCI card (ie video capture or audio, etc), hotplugging is ok, but not for GPU cards. That is normal behavior for anyone using external GPU with OSX.

**Comment by sambP** [comment]
Thanks for the fast answer!

I want to use a [dock](https://hengedocks.com/pages/vertical-macbook-pro-2016) for the MacBook. Have you any idea how i can use it? I mean, it isn't possible to reboot the mac when its not open.

**Comment by braynshock** [comment]
Well... yes, that is one of the drawbacks. Notice that the horizontal docks from henge offer a power button. I remember seeing another brand that had external power button. But that is a limitation of hacking the eGPU. For myself, when i was using eGPU with my macbook, I used a belkin tethered dock, and when i needed access tot he power button, i could open the lid, and press it, and close it.
It's not elegant, but if you can find a dock with a power button... https://hengedocks.com/pages/horizontal-macbook-pro-2016
That might be the way to make it more elegant.

**Comment by sambP** [comment]
Thanks a lot!

One last question: Do you know how to enable the HDMI sound over the GTX?

**Comment by braynshock** [comment]
I don't.
Not something i attempted. Maybe someone else can answer...
