### ISSUE TITLE
Will it work rx-480 Capitan?

### ISSUE THREAD

**Issue by Mikaoo** [goalque/automate-eGPU#50]
Hello!! and I want to say thank you for a wonderful project and good job!
Will it work on RX-480 captain or need to upgrade to the Sierra? Thank you!

**Comment by Mikaoo** [comment]
Capitan does not start, only Sierra. But I have another issue with the professionals - why Sierra hangs when booting? Only if you connect via thunderbolt hot plug. And apparently this davinci resolve does not see the second card while in the system it is detected.

**Comment by Mikaoo** [comment]
now the problem with 10.12.3 https://github.com/goalque/automate-eGPU/issues/52

**Comment by goalque** [comment]
No, you need macOS 10.12.2 or later.
