### ISSUE TITLE
not working 10.12.3 rx480

### ISSUE THREAD

**Issue by Mikaoo** [goalque/automate-eGPU#52]
not working 10.12.3 rx480 they see in the system but not used by other programs =(( will the upgrade script for 10.12.3? thank you!

**Comment by goalque** [comment]
You did not provide any information about your setup.

**Comment by Mikaoo** [comment]
Yes, forgive me, of course:
- iMac 21" 2013
- AKiTiO Thunderbolt 2 PCIe Expansion Box 
Sierra 10.12.3
- video card rx480
Install as described here
Video card installed and see in the system but not used by third-party applications. I read on one of the forums that is seen in 10.12.3
So I understand I either rearrange 10.12.2 or maybe the update will be released for the script :)

**Comment by Mikaoo** [comment]
Forgot to attach the link of what instructions I use

https://9to5mac.com/2017/01/18/hands-on-akitio-node-egpu-tubro-charge-apple-2016-macbook-pro-thunderbolt-3-video/

**Comment by goalque** [comment]
What apps? Did you set the eGPU monitor as the primary?

**Comment by Mikaoo** [comment]
No I did not. As egpu should I major in?

**Comment by goalque** [comment]
https://egpu.io/how-to-egpu-accelerated-internal-display-macos/

**Comment by Mikaoo** [comment]
Wow! Great information, thank you!

**Comment by Mikaoo** [comment]
I installed mac os 10.12.2.but I have also a problem. I'm sure I'm doing the exact same mistake. Can anyone give detailed instructions for rx470/rx480. Thank you!!!

**Comment by Mikaoo** [comment]
Forgot to specify the application davinchi resolve studio

**Comment by goalque** [comment]
The script can't solve application specific problems. Most of them are not designed to utilize eGPUs, especially if there is dGPU present.

**Comment by Mikaoo** [comment]
I have 4 days trying to figure out what the problem is. Do the instructions with the Asus gtx950 had no problems. In the list of devices the card is visible but not seen "about this Mac". If the computer to reboot when you boot the os it hangs. Please anyone have any ideas I would be very grateful, thanks!!

**Comment by goalque** [comment]
Don't trust to "About this Mac" window, it's not up-to-date. To see active GPUs, go to Hardware ->Graphics/Displays, and press Command+R to refresh the view. If the RX 480 is visible and your eGPU display output is not sluggish, then there is no problem. If the boot hangs, try re-running the script. It should work with TB1/TB2 Macs + non-XFX brand RX 480.

https://egpu.io/forums/thunderbolt-enclosures/review-akitio-node-thunderbolt-3-egpu-enclosure/#post-2839

**Comment by Mikaoo** [comment]
I will experiment and result write. Thank you!

**Comment by Mikaoo** [comment]
set a new 10.12.1
installed the script
system hangs at boot.((
screenshot put
![2017-02-22 0 43 29](https://cloud.githubusercontent.com/assets/25687516/23186539/8d927df2-f898-11e6-9d20-e3135d56009f.png)

**Comment by Mikaoo** [comment]
is it in this folder should not be AMDRadeonX4100.kekst ?
![2017-02-22 0 53 22](https://cloud.githubusercontent.com/assets/25687516/23186842/9717e32a-f899-11e6-8f7b-5ba3c4910c9b.png)

**Comment by goalque** [comment]
No, they are located in "/System/Library/Extensions/" and you should be on 10.12.2 or 10.12.3. When the system "hangs", what exactly happens? Do you see the progress bar? Wait for some minutes, it should go through. Then re-run the script, shut down, and try again. If the startup manager freezes (Option key down), your Mac is not compatible.

**Comment by Mikaoo** [comment]
hangs in the middle of the strip (from left to right)
at this point the video card increases the speed and stops, the fans stop.

**Comment by goalque** [comment]
How is your Thunder2 powered? Does it boot without the eGPU monitor?

**Comment by Mikaoo** [comment]
not sure I understand the question, you mean the power supply is external it nourishes 350 watt video card 8pin

**Comment by goalque** [comment]
Two separate questions. With a molex-to-barrel to the DC jack? And regarding the hang - if the eGPU monitor is disconnected, does the boot process still hang?

You should first install macOS 10.12.2 or 10.12.3.

**Comment by Mikaoo** [comment]
Yes, the power using the dual molex. Yes if you disconnect egup the system still hangs and does not download. Well I will set 10.12.3 Thank you my dear friend, I am not losing hope and I am sure there is a way, but I feel I am not alone in trouble, You help me a lot! Thank you!

**Comment by Mikaoo** [comment]
![img_20170222_015110](https://cloud.githubusercontent.com/assets/25687516/23188939/acc6492a-f8a1-11e6-9e3a-0abbf468b4cd.jpg)
![img_20170222_015117](https://cloud.githubusercontent.com/assets/25687516/23188943/b0d72d7c-f8a1-11e6-9fae-bd333ec4151e.jpg)
![img_20170222_015122](https://cloud.githubusercontent.com/assets/25687516/23188949/b5b0ad00-f8a1-11e6-928c-c30fd84df0f2.jpg)

**Comment by goalque** [comment]
Nice photos! I just realized it worked with a GTX 950, so this is not a power problem. It’s a kernel cache or Mac firmware problem. AMDs are not easy to get working.

**Comment by Mikaoo** [comment]
I upgraded to 10.12.3 and installed it on a new script, still hangs at boot :( Now I will try to reset the DNS cache

**Comment by Mikaoo** [comment]
dumped the nvram did not help. Yes a problem with the card 950 was not, I bought the 480 as needed for video editing more memory and read the article that there is a risk but the 480 should have no problems now scratching their heads..

**Comment by goalque** [comment]
How about "sudo ./automate-eGPU.sh -a", and restart?

**Comment by Mikaoo** [comment]
Good afternoon :)  

Yes I have tried the parameter "-a",  "m" that does not give. If You don't mind I will tell you how I set up the script, maybe I make mistake: 
1. downloaded computer 
2. connect the cable 
3. curl -o ~/Desktop/automate-eGPU.sh https://raw.githubusercontent.com/goalque/automate-eGPU/master/automate-eGPU.sh
4. cd ~/Desktop 
5. chmod +x automate-eGPU.sh 
6. sudo ./automate-eGPU.sh 
7. then turn off the computer 
8. disconnect the cable 
9. download computer 
10. connect the cable 
11. in terminal sudo ./automate-eGPU.sh 
12. overload the computer. 

When booting it hangs :(

**Comment by goalque** [comment]
Keep the TB cable connected, and use verbose mode (Command+V) to see why the boot hangs.

**Comment by Mikaoo** [comment]
Do I understand correctly (Command+V) to use when a Mac for the suspension?

**Comment by Mikaoo** [comment]
well I now understand

**Comment by Mikaoo** [comment]
![img_20170222_112856](https://cloud.githubusercontent.com/assets/25687516/23203128/305f7900-f8f2-11e6-90a1-2d76d2906097.jpg)

**Comment by Mikaoo** [comment]
can try to install 10.12.4? I can do it by clicking update I got everything ready.

**Comment by goalque** [comment]
Thanks for the input. No more rows even if you wait for 2-3 minutes? The script doesn't support 10.12.4.

**Comment by Mikaoo** [comment]
Good my friend!! I am very grateful for the help and willing to wait as much as you want!!

**Comment by Mikaoo** [comment]
all very strange, a feeling that the card is not correct installed on the system. In devices it is, but any external program can not see it hmm
![2017-02-22 12 49 53](https://cloud.githubusercontent.com/assets/25687516/23206152/a444775c-f8fd-11e6-9174-2854b4aa71f8.png)

**Comment by goalque** [comment]
Would you answer to my previous question, do you see any new rows after 2-3 minutes? There is often "busy" or "timeout" if the boot process hangs.

**Comment by Mikaoo** [comment]
Sorry, Your previous question I'm not correctly translated. After 2 minutes, that does not write in the logs. If you disable TB also changes nothing. I also found that each download is different. All the screens are different!
![img_20170222_130147](https://cloud.githubusercontent.com/assets/25687516/23206778/0907e212-f900-11e6-9618-fa090eea6e8f.jpg)
![img_20170222_130325](https://cloud.githubusercontent.com/assets/25687516/23206785/105c2712-f900-11e6-93ff-27e206cd1647.jpg)
![img_20170222_130528](https://cloud.githubusercontent.com/assets/25687516/23206796/15b85d8e-f900-11e6-9317-8abab8e259cb.jpg)

**Comment by goalque** [comment]
Doesn't look promising. It seems as if the boot hangs immediately when the eGPU tries to show login screen. The same result without the eGPU monitor? I don't know what you mean by "disable TB". Is the FileVault turned off?

**Comment by Mikaoo** [comment]
no if egpu to telocity all perfectly loaded without errors (although the script is installed) if podkluchit egpu - hang up. TB - I meant thunderbolt. When the computer froze at boot and disable the egpu thunderbolt cable from the computer continues to be in the same freeze status, it is not loaded.

**Comment by goalque** [comment]
I guess you meant "TB cable disconnected". Sorry, it's stilll unclear to me when the boot process goes through and when it doesn't.

**Comment by Mikaoo** [comment]
I wanted to say that when imac if you download is stuck I'm still waiting for a minute or two. Then I unplug the thunderbolt cable but the imac is in the same condition (not what happens). If I force the imac to overload and do not connect thunderbolt+egpu then the imac will boot fine.

**Comment by Mikaoo** [comment]
My dear friend, forgive me for my obsession but now You are my hope. If You like, I want to reach the finish and have a desire to overcome my problem I can offer You to me to connect and control my computer through teamviewer or a similar program. If You are confused by this and You don't want to do that I understand, anyway You are doing a lot for me, thank you!

**Comment by Mikaoo** [comment]
surprisingly, I found that I deleted using the command "-uninstall" overloaded imac (thunderbolt+egpu plugged in) the computer starts !but! in the list of devices my 480 is present and this suggests that the script is not correct for me puts the driver? is there any way to manually do everything? What do you think?
![2017-02-22 14 33 20](https://cloud.githubusercontent.com/assets/25687516/23209899/41ec0b1a-f90c-11e6-8a93-17c1052c362b.png)

**Comment by Mikaoo** [comment]
read, perhaps my problem with freezing can be solved using Clover EFI bootloader..

**Comment by goalque** [comment]
It's a known bug that -uninstall doesn't restore all the original files with AMD cards. Don't mess up your system with Clover, it's meant for hackintoshes, and there is similar error:

https://www.tonymacx86.com/threads/gigabyte-z170mx-gaming-5-sierra-install-fail-ioconsoleusers-gioscreenlockstate-3-hs-0-bs-0-now-0.214715/

**Comment by Mikaoo** [comment]
thank you for a reference now will study, I connected an external monitor to 480 and it is not showing.. weird. map new store :)

**Comment by Mikaoo** [comment]
dear, goalque, I read Your link and I'm desperate, I don't know what to do next ;(

**Comment by Mikaoo** [comment]
What do you think of the experiment to install windows and try it?

**Comment by Mikaoo** [comment]
sadly, Windows is not supported by this device Akitio :(

**Comment by Mikaoo** [comment]
what I have found: according to the instructions Above I can credit it more carefully studied. The guy was complaining that his motherboard has responded to Sierra (there was an error "OConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0") but in the system of capitan there was no error. I regained the captain 10.11.6 and I downloaded imac well! If you go back to my original question can we say that if the device list is present rx-480 that I built egpu successfully? If you run luxmark I don't see a new card. Run "davinci resolve studio," he rx-480 is also not visible :( If anyone thought?

**Comment by goalque** [comment]
RX 480 requires at least macOS 10.12.2. You may have better luck with older cards, such as HD 7950/HD 7970. If not, your Mac is not compatible.

**Comment by Mikaoo** [comment]
уже подыскиваю

Yes I already look for another very sorry to sell this( thanks for the help!!

**Comment by Mikaoo** [comment]
The card was the artifacts...

**Comment by Mikaoo** [comment]
Maybe wine in my unit or is the production of a marriage do you think?

**Comment by goalque** [comment]
Your translator produces funny words. Let's stay in topic. What's your new card?

**Comment by Mikaoo** [comment]
I decided to sell 480 Map Check. When you run the bios appeared mesh grille, strips, etc. on the screen. And I think it's a marriage of production, or my fault?

**Comment by goalque** [comment]
Your translator has a sense of humour :) Sorry, I don't understand the semantics of your sentence structure. I close this issue. Thanks.

**Comment by Mikaoo** [comment]
I replaced a defective video card new, I now have the acceleration, WOW!!!!
