### ISSUE TITLE
Not working on high Sierra(10.13.2)

### ISSUE THREAD

**Issue by Zzm317** [goalque/automate-eGPU#73]
***      automate-eGPU.sh v1.0.1      ***
* (c) 2016, 2017 by Goalque & FricoRico *
*****************************************
Detected eGPU
 GP104 [GeForce GTX 1070]
Current OS X
 10.13.2 17C88
Previous OS X
 [not found]
Latest installed Nvidia web driver
 Version: 378.10.10.10.25.102
 Source: 3rd Party
 Install Date: 2017/12/20 上午1:44

You are running official Nvidia driver.
Checking IOPCITunnelCompatible keys...

IOPCITunnelCompatible mods done.
Rebuilding caches...
Kext with invalid signatured (-67030) allowed: <OSKext 0x7fedde6172e0 [0x7fffb1217980]> { URL = "NVDAStartup.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.nvidia.NVDAStartup" }
Kext with invalid signatured (-67030) allowed: <OSKext 0x7fedde593d40 [0x7fffb1217980]> { URL = "IONDRVSupport.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IONDRVSupport" }
Kext with invalid signatured (-67030) allowed: <OSKext 0x7fede05cd750 [0x7fffb1217980]> { URL = "AppleGraphicsControl.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.driver.AppleGraphicsControl" }
Kext with invalid signatured (-67030) allowed: <OSKext 0x7fede05f26c0 [0x7fffb1217980]> { URL = "AppleGraphicsDevicePolicy.kext/ -- file:///System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/", ID = "com.apple.driver.AppleGraphicsDevicePolicy" }
All ready. Please restart the Mac.

**Comment by smoothdvd** [comment]
Same. After install automate-eGPU, booting halts at Apple logo.

**Comment by goalque** [comment]
https://egpu.io/forums/mac-setup/automate-egpu-sh-is-reborn-with-amd-polaris-fiji-support-for-macos/#post-1487

General instructions (OS X 10.9.5 – **macOS 10.12.*** )

-> **This script is not applicable to High Sierra.**
