### ISSUE TITLE
SetIOPCIMatch() function doesn't work appropriately with Nvidia dGPU Macs

### ISSUE THREAD

**Issue by goalque** [goalque/automate-eGPU#8]
http://forum.techinferno.com/mac-os-x-discussion/10289-script-automating-installation-egpu-os-x-inc-display-output-24.html#post145829

**Comment by agosto-levitomes** [comment]
Workaround for Nvidia dGPU equipped Macs:
uninstall v0.9.7 with `-uninstall option`
install v0.9.6
(This is just a note so future users don't need to dig into that thread to find the workaround.)

**Comment by goalque** [comment]
Fixed.
